version: "3.4"

services:
  hivefrontend:
    build: ./hive-frontend
    environment:
      GRAFANA_ADDR: http://localhost:3000
    volumes:
      - ./hive-frontend:/usr/src/app/
    ports:
      - "80:80"
    networks:
      - default
      - dashnet

  proxybackend:
    build: ./proxy-backend
    volumes:
      - ./proxy-backend:/usr/src/app/
    ports:
      - "8080:8080"
    networks:
      - default
      - dashnet
    restart: on-failure

  grafana:
    build: './grafana'
    container_name: grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-simple-json-datasource,grafana-piechart-panel
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    ports:
      - "3000:3000"
    volumes:
      - GrafanaVol:/var/lib/grafana
      - ./grafana/dashboards/:/var/lib/grafana/dashboards
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - default
      - dashnet

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Testtest123
      MONGO_LORA_USERNAME: loraUser
      MONGO_LORA_PASSWORD: Testtest123
      MONGO_LORA_DB_NAME: loradb
    ports:
      - "27017:27017"
    restart: on-failure:5
    volumes:
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
      - MongoDBVol:/data/db
    networks:
      - default
      - dashnet

networks:
  dashnet:

volumes:
  GrafanaVol:
  MongoDBVol:
